sudo pacman -S xfce4-power-manager 
sudo pacman -S polybar 
sudo pacman -S dunst
sudo pacman -S mpd 
sudo pacman -S mpc
sudo pacman -S maim 
sudo pacman -S xclip 
sudo pacman -S viewnior
sudo pacman -S ksuperkey
sudo pacman -S networkmanager-dmenu-git
sudo pacman -S xmlstarlet
